Repository prgrms-web-devcourse-final-project/WEB1_1_Recorder_BE, pull requests merged in 2024-12, with the labels that each got.

#32 Refactor/#31 답변 리팩토링
  RevUp-api/src/main/java/com/revup/answer/dto/request/AnswerCreateRequest.java
  RevUp-api/src/main/java/com/revup/answer/dto/response/AnswerDetailsResponse.java
  RevUp-api/src/main/java/com/revup/answer/mapper/AnswerCodeMapper.java
  RevUp-api/src/main/java/com/revup/answer/usecase/CreateAnswerUseCase.java
  RevUp-api/src/main/java/com/revup/question/dto/response/QuestionDetailsResponse.java
  RevUp-domain/src/main/java/com/revup/answer/entity/Answer.java
  RevUp-domain/src/main/java/com/revup/answer/entity/AnswerCode.java
  RevUp-domain/src/main/java/com/revup/answer/service/AnswerService.java
  RevUp-domain/src/main/java/com/revup/question/repository/CustomQuestionRepositoryImpl.java
Labels: refactor, 믿음

#41 hotfix: #40 @SecurityUser 에러 수정
  RevUp-common/src/main/java/com/revup/config/WebConfig.java
  RevUp-common/src/main/java/com/revup/handler/SecurityUserArgumentResolver.java
  RevUp-domain/src/main/java/com/revup/user/repository/UserRepository.java
  RevUp-security/src/main/java/com/revup/utils/SecurityUserArgumentResolverAdaptor.java
Labels: hotfix, 준호

#43 HOTFIX: #42 피드백 관련 api 오류 수정, 작동 확인
  RevUp-api/src/main/java/com/revup/feedback/controller/FeedbackController.java
  RevUp-api/src/main/java/com/revup/feedback/controller/MentorController.java
  RevUp-api/src/main/java/com/revup/feedback/usecase/GetMentorListUseCase.java
  RevUp-security/src/main/java/com/revup/constants/SecurityUrlEndpoint.java
Labels: hotfix, 민우

#45 Feature/#25 좋아요 구현
  RevUp-api/src/main/java/com/revup/heart/controller/HeartController.java
  RevUp-api/src/main/java/com/revup/heart/dto/request/HeartCreateRequest.java
  RevUp-api/src/main/java/com/revup/heart/dto/response/HeartIdResponse.java
  RevUp-api/src/main/java/com/revup/heart/mapper/HeartMapper.java
  RevUp-api/src/main/java/com/revup/heart/usecase/CreateHeartUseCase.java
  RevUp-api/src/main/java/com/revup/heart/usecase/DeleteHeartUseCase.java
  RevUp-common/src/main/java/com/revup/error/ErrorCode.java
  RevUp-domain/src/main/java/com/revup/answer/entity/Answer.java
  RevUp-domain/src/main/java/com/revup/answer/exception/AnswerNotFoundException.java
  RevUp-domain/src/main/java/com/revup/heart/HeartType.java
  RevUp-domain/src/main/java/com/revup/heart/entity/Heart.java
  RevUp-domain/src/main/java/com/revup/heart/enums/HeartType.java
  RevUp-domain/src/main/java/com/revup/heart/exception/HeartExistException.java
  RevUp-domain/src/main/java/com/revup/heart/exception/HeartNotFoundException.java
  RevUp-domain/src/main/java/com/revup/heart/exception/InvalidHeartTypeException.java
  RevUp-domain/src/main/java/com/revup/heart/port/HeartPort.java
  RevUp-domain/src/main/java/com/revup/heart/repository/HeartRepository.java
  RevUp-domain/src/main/java/com/revup/heart/service/HeartService.java
  RevUp-domain/src/main/resources/application-domain.yml
  RevUp-infra/src/main/java/com/revup/heart/adaptor/HeartAdaptor.java
  RevUp-infra/src/main/java/com/revup/heart/batch/HeartBatchScheduler.java
  RevUp-infra/src/main/java/com/revup/heart/config/SchedulerConfig.java
  RevUp-infra/src/main/java/com/revup/redis/config/RedisConfig.java
  RevUp-infra/src/main/java/com/revup/redis/config/RedissonConfig.java
Labels: feat, 믿음

#50 hotfix: #49 구글 소셜 로그인시 이미지 사진이 없는 사용자의 소셜 로그인 및 회원가입 에러 현상 수정
  RevUp-security/src/main/java/com/revup/oauth/service/UserCreator.java
Labels: hotfix, 준호

#54 Feat/#44 채팅 구현
  RevUp-api/src/main/java/com/revup/chat/.gitkeep
  RevUp-api/src/main/java/com/revup/chat/controller/ChatController.java
  RevUp-api/src/main/java/com/revup/chat/dto/ChatMessageDto.java
  RevUp-api/src/main/java/com/revup/chat/dto/ChatRoomGetRequest.java
  RevUp-api/src/main/java/com/revup/chat/dto/MessageType.java
  RevUp-api/src/main/java/com/revup/chat/mapper/ChatMapper.java
  RevUp-api/src/main/java/com/revup/chat/usecase/CreateChatUseCase.java
  RevUp-api/src/main/java/com/revup/chat/usecase/GetChatMessagesUseCase.java
  RevUp-api/src/main/java/com/revup/chat/usecase/GetChatRoomUseCase.java
  RevUp-api/src/main/java/com/revup/chat/usecase/GetMyChatRoomListUseCase.java
  RevUp-api/src/main/java/com/revup/config/WebSocketConfig.java
  RevUp-common/src/main/java/com/revup/error/ErrorCode.java
  RevUp-domain/src/main/java/com/revup/chat/adaptor/ChatRoomAdaptor.java
  RevUp-domain/src/main/java/com/revup/chat/adaptor/ChatRoomBelongAdaptor.java
  RevUp-domain/src/main/java/com/revup/chat/entity/ChatMessage.java
  RevUp-domain/src/main/java/com/revup/chat/entity/ChatMessageRead.java
  RevUp-domain/src/main/java/com/revup/chat/entity/ChatRoom.java
  RevUp-domain/src/main/java/com/revup/chat/entity/ChatRoomBelong.java
  RevUp-domain/src/main/java/com/revup/chat/repository/.gitkeep
  RevUp-domain/src/main/java/com/revup/chat/repository/ChatMessageReadRepository.java
  RevUp-domain/src/main/java/com/revup/chat/repository/ChatMessageRepository.java
  RevUp-domain/src/main/java/com/revup/chat/repository/ChatRoomBelongRepository.java
  RevUp-domain/src/main/java/com/revup/chat/repository/ChatRoomRepository.java
  RevUp-domain/src/main/java/com/revup/chat/repository/CustomChatRoomBelongRepository.java
  RevUp-domain/src/main/java/com/revup/chat/repository/CustomChatRoomBelongRepositoryImpl.java
  RevUp-domain/src/main/java/com/revup/chat/service/.gitkeep
  RevUp-domain/src/main/java/com/revup/chat/service/ChatService.java
  RevUp-domain/src/main/java/com/revup/chat/service/response/ChatMessageResponse.java
  RevUp-domain/src/main/java/com/revup/chat/service/response/ChatRoomListResponse.java
  RevUp-domain/src/main/java/com/revup/feedback/entity/FeedbackSkillStack.java
  RevUp-domain/src/main/java/com/revup/feedback/service/FeedbackCodeService.java
  RevUp-security/src/main/java/com/revup/constants/SecurityUrlEndpoint.java
Labels: feat, 민우

#55 Feature/#53 총 답변 수 채택 답변수 컬럼 추가
  RevUp-api/src/main/java/com/revup/answer/controller/AnswerController.java
  RevUp-api/src/main/java/com/revup/answer/dto/request/AnswerCreateRequest.java
  RevUp-api/src/main/java/com/revup/answer/dto/request/AnswerDeleteRequest.java
  RevUp-api/src/main/java/com/revup/answer/dto/request/AnswerUpdateRequest.java
  RevUp-api/src/main/java/com/revup/answer/dto/response/AnswerDetailsResponse.java
  RevUp-api/src/main/java/com/revup/answer/mapper/AnswerMapper.java
  RevUp-api/src/main/java/com/revup/question/controller/QuestionController.java
  RevUp-api/src/main/java/com/revup/question/dto/request/QuestionDeleteRequest.java
  RevUp-domain/build.gradle
  RevUp-domain/src/main/java/com/revup/answer/dto/AnswerUpdateInfo.java
  RevUp-domain/src/main/java/com/revup/answer/entity/Answer.java
  RevUp-domain/src/main/java/com/revup/answer/repository/AnswerRepository.java
  RevUp-domain/src/main/java/com/revup/answer/service/AnswerService.java
  RevUp-domain/src/main/java/com/revup/question/entity/Question.java
  RevUp-domain/src/main/java/com/revup/question/entity/QuestionCode.java
  RevUp-domain/src/main/java/com/revup/question/entity/QuestionImage.java
  RevUp-domain/src/main/java/com/revup/question/repository/QuestionCodeRepository.java
  RevUp-domain/src/main/java/com/revup/question/repository/QuestionImageRepository.java
  RevUp-domain/src/main/java/com/revup/question/service/QuestionService.java
  RevUp-domain/src/main/java/com/revup/user/entity/Profile.java
  RevUp-domain/src/main/java/com/revup/user/entity/User.java
  RevUp-domain/src/main/java/com/revup/user/exception/UserIdNotFoundException.java
  RevUp-domain/src/main/java/com/revup/user/repository/UserRepository.java
  RevUp-domain/src/main/resources/application-domain.yml
Labels: feat, refactor, 믿음

#72 fix: 낙관적 락 -> 비관적 락으로 변경 (#71)
  RevUp-domain/src/main/java/com/revup/answer/service/AnswerService.java
  RevUp-domain/src/main/java/com/revup/common/config/RetryConfig.java
  RevUp-domain/src/main/java/com/revup/question/entity/Question.java
  RevUp-domain/src/main/java/com/revup/question/repository/QuestionRepository.java
Labels: hotfix, 믿음

#75 refactor: 기술 스택 리팩토링 (#74)
  RevUp-api/src/main/java/com/revup/common/skillstack/controller/SkillStackController.java
  RevUp-api/src/main/java/com/revup/email/CertificationNumberEventListener.java
  RevUp-api/src/main/java/com/revup/question/controller/QuestionController.java
  RevUp-api/src/main/java/com/revup/question/dto/response/QuestionBriefResponse.java
  RevUp-api/src/main/java/com/revup/question/dto/response/QuestionDetailsResponse.java
  RevUp-api/src/main/java/com/revup/question/mapper/QuestionMapper.java
  RevUp-api/src/main/java/com/revup/skillstack/controller/SkillStackController.java
  RevUp-api/src/main/java/com/revup/skillstack/model/mapper/SkillStackMapper.java
  RevUp-api/src/main/java/com/revup/skillstack/model/response/SkillStackResponse.java
  RevUp-api/src/main/java/com/revup/skillstack/usecase/SkillStackUseCase.java
  RevUp-api/src/main/java/com/revup/user/service/GetMyInfoUseCase.java
  RevUp-api/src/main/java/com/revup/user/service/UpdateUserUseCase.java
  RevUp-domain/src/main/java/com/revup/question/repository/QuestionRepository.java
  RevUp-domain/src/main/java/com/revup/question/service/QuestionService.java
  RevUp-domain/src/main/resources/application-domain.yml
  RevUp-security/src/main/java/com/revup/constants/SecurityUrlEndpoint.java
Labels: refactor, 믿음

#76 Feat/#73 추가 요구사항 구현
  RevUp-api/src/main/java/com/revup/chat/controller/ChatController.java
  RevUp-api/src/main/java/com/revup/feedback/controller/MentorController.java
  RevUp-api/src/main/java/com/revup/feedback/mapper/FeedbackMapper.java
  RevUp-api/src/main/java/com/revup/feedback/mapper/FeedbackSkillStackMapper.java
  RevUp-api/src/main/java/com/revup/feedback/mapper/MentorMapper.java
  RevUp-api/src/main/java/com/revup/feedback/mapper/MentorSkillStackMapper.java
  RevUp-api/src/main/java/com/revup/feedback/request/FeedbackCreateRequest.java
  RevUp-api/src/main/java/com/revup/feedback/request/MentorCreateRequest.java
  RevUp-api/src/main/java/com/revup/feedback/usecase/CreateFeedbackUseCase.java
  RevUp-api/src/main/java/com/revup/feedback/usecase/CreateMentorUseCase.java
  RevUp-api/src/main/java/com/revup/feedback/usecase/GetMentorListUseCase.java
  RevUp-domain/src/main/java/com/revup/feedback/entity/Feedback.java
  RevUp-domain/src/main/java/com/revup/feedback/entity/FeedbackSkillStack.java
  RevUp-domain/src/main/java/com/revup/feedback/entity/Mentor.java
  RevUp-domain/src/main/java/com/revup/feedback/entity/MentorSkillStack.java
  RevUp-domain/src/main/java/com/revup/feedback/repository/CustomMentorRepositoryImpl.java
  RevUp-domain/src/main/java/com/revup/feedback/repository/FeedbackRepository.java
  RevUp-domain/src/main/java/com/revup/feedback/repository/FeedbackSkillStackRepository.java
  RevUp-domain/src/main/java/com/revup/feedback/repository/MentorSkillStackRepository.java
  RevUp-domain/src/main/java/com/revup/feedback/service/FeedbackService.java
  RevUp-domain/src/main/java/com/revup/feedback/service/FeedbackSkillStackService.java
  RevUp-domain/src/main/java/com/revup/feedback/service/MentorSkillStackService.java
  RevUp-domain/src/main/java/com/revup/feedback/service/response/FeedbackResponse.java
  RevUp-domain/src/main/java/com/revup/feedback/service/response/MentorResponse.java
Labels: feat, refactor, 민우

#77 Feat/#58 기능 추가 및 테스트 코드 작성
  RevUp-api/src/main/java/com/revup/answer/dto/response/AnswerDetailsResponse.java
  RevUp-api/src/main/java/com/revup/auth/model/mapper/AuthMapper.java
  RevUp-api/src/main/java/com/revup/auth/service/AuthenticationUseCase.java
  RevUp-api/src/main/java/com/revup/user/model/request/UpdateProfileRequest.java
  RevUp-api/src/main/java/com/revup/user/service/UpdateUserUseCase.java
  RevUp-domain/src/main/java/com/revup/achievement/service/AchievementProgressCalculator.java
  RevUp-domain/src/main/java/com/revup/user/constant/UserConstants.java
  RevUp-domain/src/main/java/com/revup/user/entity/User.java
  RevUp-domain/src/main/java/com/revup/user/service/UserDomainImpl.java
  RevUp-security/src/main/java/com/revup/oauth/handler/Oauth2AuthenticationSuccessHandler.java
Labels: refactor, 준호

#84 refactor: #82 토큰 방식으로 전환 진행 중(현재는 토큰과 header가 동시에 있음)
  RevUp-api/src/main/java/com/revup/auth/controller/AuthController.java
  RevUp-api/src/main/java/com/revup/global/exception/GlobalExceptionHandler.java
  RevUp-security/src/main/java/com/revup/config/RevUpAuthenticationEntryPoint.java
  RevUp-security/src/main/java/com/revup/jwt/RevUpJwtValidator.java
  RevUp-security/src/main/java/com/revup/jwt/filter/RevUpJwtFilter.java
  RevUp-security/src/main/java/com/revup/oauth/handler/Oauth2AuthenticationSuccessHandler.java
  RevUp-security/src/main/java/com/revup/utils/CookieUtils.java
Labels: refactor, 준호
